name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://golang:latest
        with:
          args: go run build.go assets
      - name: golangci-runner
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}

